apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    labels:
        app: book-a-room
spec:
    replicas: 1
    selector:
        matchLabels:
            app: book-a-room
    template:
        metadata:
            labels:
                app: book-a-room
        spec:
            containers:
                - name: book-a-room
                  image: acrbookaroomprod001.azurecr.io/book
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
    selector:
        app: book-a-room
        type: LoadBalancer
